spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgres}
    username: ${DB_USER:reto}
    password: ${DB_PASSWORD:reto}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
